drop table IF EXISTS DOMICILIOS;
create TABLE DOMICILIOS (ID INT AUTO_INCREMENT PRIMARY KEY, CALLE VARCHAR(100) NOT NULL, NUMERO INT NOT NULL, LOCALIDAD VARCHAR(100) NOT NULL, PROVINCIA VARCHAR(100) NOT NULL);

drop table IF EXISTS PACIENTES;
create TABLE PACIENTES (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL, DNI VARCHAR(100) NOT NULL, FECHA DATE NOT NULL, DOMICILIO_ID INT);


DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS(ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA NUMERIC NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);


-- para test --
INSERT INTO  ODONTOLOGOS(MATRICULA, NOMBRE, APELLIDO) VALUES ('1234', 'Julian', 'Delgado'), ('4567', 'Serrana', 'Marset');


INSERT INTO PACIENTES(NOMBRE, APELLIDO, DNI, FECHA, DOMICILIO_ID) VALUES ('Serra', 'Lopez', '11111111', '2023-02-01', 2);
INSERT INTO PACIENTES(NOMBRE, APELLIDO, DNI, FECHA, DOMICILIO_ID) VALUES ('Dei', 'Perez', '22222222', '2023-02-01', 2);

DROP TABLE IF EXISTS TURNOS;
CREATE TABLE TURNOS(ID INT AUTO_INCREMENT PRIMARY KEY, FECHA DATETIME NOT NULL, ODONTOLOGO_ID INT, PACIENTE_ID INT);

INSERT INTO TURNOS (FECHA, ODONTOLOGO_ID, PACIENTE_ID) VALUES ('2023-06-05 10:55:00', 2, 1);